services:
  - type: web
    name: plates-scraper
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y wget gnupg2 curl unzip
      wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      apt install -y ./google-chrome-stable_current_amd64.deb
      CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+' | head -1)
      wget https://chromedriver.storage.googleapis.com/${CHROME_VERSION}/chromedriver_linux64.zip || wget https://chromedriver.storage.googleapis.com/$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
      unzip chromedriver_linux64.zip
      mv chromedriver /usr/bin/chromedriver
      chmod +x /usr/bin/chromedriver
      which google-chrome
      which chromedriver
      google-chrome --version
      chromedriver --version
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: CHROME_BIN
        value: /usr/bin/google-chrome
      - key: CHROMEDRIVER_PATH
        value: /usr/bin/chromedriver
